extends Node

signal mainMenu_beginGame
signal mainMenu_quit

signal inGame_playerStart
signal inGame_flappyBirdDied
signal inGame_flappyPassedPipe
signal inGame_goToMainMenu

signal universal_triggerSave